// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://giiaaubgqjexbinyfxkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpaWFhdWJncWpleGJpbnlmeGtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNDM0NTAsImV4cCI6MjA1NzcxOTQ1MH0._m5UmsVg94fHAb7XVk6GoaWuOajR89BXMeU3LneQLj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});